//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MF0493_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Empresas = new HashSet<Empresa>();
        }
    
        public string username { get; set; }
        public string email { get; set; }
        public string passwd { get; set; }
        public bool activo { get; set; }
        public Nullable<System.DateTime> lastlogin { get; set; }
    
        public virtual ICollection<Empresa> Empresas { get; set; }
    }
}
